# Generated by Django 2.2.10 on 2021-04-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_comptence', models.CharField(max_length=20, null=True)),
                ('competences', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_emp', models.CharField(default=None, max_length=20)),
                ('cuid_emp', models.CharField(default=None, max_length=20)),
                ('genre', models.CharField(default=None, max_length=20)),
                ('nom_emp', models.CharField(default=None, max_length=50, verbose_name='nom_emp')),
                ('id_dept', models.CharField(default=None, max_length=20)),
                ('nom_dept', models.CharField(default=None, max_length=100)),
                ('matricul_resp', models.CharField(default=None, max_length=50)),
                ('nom_resp', models.CharField(default=None, max_length=50)),
                ('id_dept_parent', models.CharField(default=None, max_length=20)),
                ('nom_dept_parent', models.CharField(default=None, max_length=50)),
                ('name_bu', models.CharField(default=None, max_length=50)),
                ('name_direction', models.CharField(default=None, max_length=50)),
                ('resp_bu', models.CharField(default=None, max_length=50)),
                ('mail', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, verbose_name='E_mail')),
                ('nb_exp', models.CharField(default=None, max_length=20)),
                ('seniorite', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
