# Generated by Django 2.2.10 on 2021-04-17 01:47

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210417_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comeptence',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True,  null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True,  null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='adate',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True,  null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='datede',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True,  null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True,  null=True, size=None),
        ),
    ]
